# Generated by Django 3.2.8 on 2021-11-09 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bids_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidAmount', models.PositiveBigIntegerField(null=True)),
                ('dateTime_bid', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_master')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bids_master',
            },
        ),
        migrations.CreateModel(
            name='order_item_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(blank=True, null=True)),
                ('amount', models.PositiveBigIntegerField(null=True)),
                ('bid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BidDetails.bids_master')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_master')),
            ],
            options={
                'db_table': 'order_item_master',
            },
        ),
    ]
