# Generated by Django 3.2.8 on 2021-11-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, null=True, unique=True)),
            ],
            options={
                'db_table': 'Category_master',
            },
        ),
        migrations.CreateModel(
            name='subcategory_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=200, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category_master')),
            ],
            options={
                'db_table': 'subcategory_master',
            },
        ),
        migrations.CreateModel(
            name='product_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('model_year', models.IntegerField(blank=True, default=2000, null=True)),
                ('running_km', models.IntegerField(blank=True, default=0)),
                ('fuel_type', models.CharField(blank=True, max_length=30, null=True)),
                ('p_reg_date', models.DateField()),
                ('start_dateTimeInfo', models.DateTimeField()),
                ('basePrice', models.IntegerField(blank=True, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory_master')),
            ],
            options={
                'db_table': 'product_master',
            },
        ),
    ]
