# Generated by Django 3.2.8 on 2021-11-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dateTimeInfo', models.DateTimeField()),
                ('payment_dateTimeInfo', models.DateTimeField()),
                ('basePrice', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_master',
            name='basePrice',
        ),
        migrations.RemoveField(
            model_name='product_master',
            name='start_dateTimeInfo',
        ),
    ]
