# Generated by Django 3.2.8 on 2021-11-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211112_2308'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auction_info',
            table='Auction_info',
        ),
    ]
