# Generated by Django 3.2.8 on 2021-11-13 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auction_info_prodct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_info',
            name='prodct',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product_master'),
        ),
    ]
