# Generated by Django 3.2.8 on 2021-11-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_auction_info_prodct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_info',
            old_name='prodct',
            new_name='product',
        ),
    ]
